import type { Gene } from "@signal/core";

export type { Gene } from "@signal/core";

export const GENES: Gene[] = [
  {
    id: "attention",
    label: "Attention",
    family: "attention",
    maturity: "foundational",
    blurb:
      "The mechanism that lets a model weigh every token against every other token, deciding what to focus on.",
    aliases: [
      "attention",
      "self attention",
      "self-attention",
      "multi head attention",
      "multi-head attention",
      "mha",
      "attention mechanism",
    ],
    keywords: [
      "attention score",
      "query key value",
      "qkv",
      "scaled dot product",
      "softmax over query",
    ],
    prerequisites: [],
  },
  {
    id: "kv-cache",
    label: "KV Cache",
    family: "memory",
    maturity: "active",
    blurb:
      "The key-value tensor cache that trades memory for speed, so past tokens are never recomputed.",
    aliases: ["kv cache", "kv-cache", "key value cache", "kv tensors"],
    keywords: ["key-value cache", "cache reuse", "kvcache"],
    prerequisites: ["attention"],
  },
  {
    id: "paged-attention",
    label: "Paged Attention",
    family: "memory",
    maturity: "emerging",
    blurb:
      "Manages the KV cache in fixed-size blocks like virtual memory pages, eliminating fragmentation and waste.",
    aliases: ["paged attention", "paged-attention", "pagedattention", "paged kv"],
    keywords: ["block table", "memory fragmentation", "paged"],
    prerequisites: ["kv-cache"],
  },
  {
    id: "prefix-caching",
    label: "Prefix Caching",
    family: "memory",
    maturity: "emerging",
    blurb:
      "Reuses the cached computation of shared prompt prefixes so repeated system prompts cost nothing.",
    aliases: ["prefix caching", "prefix-caching", "prefix cache", "automatic prefix caching"],
    keywords: ["prompt prefix", "shared prefix", "radix tree", "prefix tree"],
    prerequisites: ["kv-cache"],
  },
  {
    id: "continuous-batching",
    label: "Continuous Batching",
    family: "serving",
    maturity: "active",
    blurb:
      "Adds and evicts requests at every decoding step, so a GPU never idles waiting for the slowest request to finish.",
    aliases: [
      "continuous batching",
      "continuous-batching",
      "dynamic batching",
      "incremental batching",
    ],
    keywords: ["batch scheduling", "iteration level scheduling", "orch-burst"],
    prerequisites: ["attention"],
  },
  {
    id: "serving-frameworks",
    label: "Serving Frameworks",
    family: "serving",
    maturity: "active",
    blurb:
      "The runtime layer (vLLM, TensorRT-LLM, SGLang, TGI) that turns a raw model into an HTTP endpoint.",
    aliases: [
      "vllm",
      "sglang",
      "tensorrt-llm",
      "text generation inference",
      "tgi",
      "llama.cpp",
      "inference server",
    ],
    keywords: [
      "model serving",
      "llm serving",
      "openai-compatible",
      "openai compatible endpoint",
      "engine",
    ],
    prerequisites: ["continuous-batching"],
  },
  {
    id: "quantization",
    label: "Quantization",
    family: "compression",
    maturity: "active",
    blurb:
      "Represents weights in lower precision (int8, fp4, 8-bit) so a model fits memory and runs faster.",
    aliases: [
      "quantization",
      "4-bit",
      "8-bit",
      "awq",
      "gptq",
      "gguf",
      "bitsandbytes",
      "fp8",
      "llama q4",
      "int8",
    ],
    keywords: [
      "quantized weights",
      "weight precision",
      "calibration",
      "quantization aware",
      "groupwise",
    ],
    prerequisites: [],
  },
  {
    id: "distillation",
    label: "Distillation",
    family: "compression",
    maturity: "emerging",
    blurb:
      "Trains a small model to imitate a big one, preserving most of the knowledge at a fraction of the cost.",
    aliases: ["distillation", "knowledge distillation", "distilled model"],
    keywords: ["teacher model", "student model", "distill"],
    prerequisites: [],
  },
  {
    id: "flashattention",
    label: "FlashAttention",
    family: "compute",
    maturity: "active",
    blurb:
      "IO-aware attention kernels that factor the softmax out of memory, making long-sequence training and serving cheap.",
    aliases: ["flashattention", "flash attention", "flash-attention", "fusion attention"],
    keywords: ["io-aware", "io aware", "cuda kernels for attention", "attention kernel"],
    prerequisites: ["attention"],
  },
  {
    id: "gpu-kernels",
    label: "GPU Kernels",
    family: "compute",
    maturity: "active",
    blurb:
      "Hand-tuned CUDA/Triton kernels that fuse, vectorize and overlap operations to extract every FLOP from the hardware.",
    aliases: ["cuda kernel", "triton", "kernel fusion", "gpu kernel", "cublas", "cudnn"],
    keywords: ["kernel launch overhead", "memory bandwidth bound", "compute bound", "warp", "tile"],
    prerequisites: [],
  },
  {
    id: "speculative-decoding",
    label: "Speculative Decoding",
    family: "dynamics",
    maturity: "emerging",
    blurb:
      "A draft model proposes tokens while the slow big model verifies in parallel, speeding up generation at zero quality cost.",
    aliases: [
      "speculative decoding",
      "speculative-decoding",
      "speculative decoding",
      "draft and verify",
      "draft-and-verify",
      "medusa",
      "eagle",
      "lookahead decoding",
    ],
    keywords: [
      "draft model",
      "verification pass",
      "acceptance rate",
      "parallel verification",
      "spinning",
      "speculate",
    ],
    prerequisites: ["kv-cache", "continuous-batching"],
  },
  {
    id: "moe-routing",
    label: "Mixture-of-Experts Routing",
    family: "routing",
    maturity: "emerging",
    blurb:
      "Splits the model into expert sub-networks and routes each token to a small subset, multiplying capacity per FLOP.",
    aliases: [
      "moe",
      "mixture of experts",
      "mixture-of-experts",
      "expert routing",
      "mixtral",
      "8x7b",
      "8x22b",
      "routing network",
    ],
    keywords: ["expert layers", "router", "top-k routing", "top k routing", "sparse experts"],
    prerequisites: [],
  },
  {
    id: "tensor-parallelism",
    label: "Tensor Parallelism",
    family: "scale",
    maturity: "active",
    blurb: "Shards a single tensor across GPUs so one model can spread over many accelerators.",
    aliases: [
      "tensor parallelism",
      "tensor-parallelism",
      "tp",
      "megatron",
      "pipeline parallelism",
      "sequence parallelism",
    ],
    keywords: ["all-reduce", "reduce scatter", "weight sharding"],
    prerequisites: ["attention"],
  },
  {
    id: "long-context",
    label: "Long Context",
    family: "memory",
    maturity: "emerging",
    blurb:
      "Everything that raises the context window: position extrapolation, ring attention, and the pressure it puts on caches.",
    aliases: [
      "long context",
      "long-context",
      "128k",
      "context window",
      "ring attention",
      "yarn",
      "rope",
    ],
    keywords: ["positional interpolation", "context dilation", "context scaling", "long sequence"],
    prerequisites: ["paged-attention"],
  },
];

export const GENE_BY_ID: Record<string, Gene> = Object.fromEntries(GENES.map((g) => [g.id, g]));
