export const GENES_MAP: Record<string, { color: string; label: string }> = {
  attention: { color: "#22d3ee", label: "Attention" },
  "kv-cache": { color: "#fbbf24", label: "KV Cache" },
  "paged-attention": { color: "#fcd34d", label: "Paged Attention" },
  "prefix-caching": { color: "#fde68a", label: "Prefix Caching" },
  "continuous-batching": { color: "#34d399", label: "Continuous Batching" },
  "serving-frameworks": { color: "#6ee7b7", label: "Serving Frameworks" },
  quantization: { color: "#fb7185", label: "Quantization" },
  distillation: { color: "#fda4af", label: "Distillation" },
  flashattention: { color: "#a78bfa", label: "FlashAttention" },
  "gpu-kernels": { color: "#c4b5fd", label: "GPU Kernels" },
  "speculative-decoding": { color: "#a3e635", label: "Speculative Decoding" },
  "moe-routing": { color: "#fb923c", label: "Mixture-of-Experts" },
  "tensor-parallelism": { color: "#38bdf8", label: "Tensor Parallelism" },
  "long-context": { color: "#f472b6", label: "Long Context" },
};
