import type { Content, SourceType } from "@signal/core";
import { contentId } from "@signal/core";

type SeedInput = {
  source: string;
  sourceType?: SourceType;
  title: string;
  slug: string;
  date: string;
  body: string;
  author?: string;
  tags?: string[];
  codeBlocks?: string[];
};

function siteFor(source: string): string {
  const sites: Record<string, string> = {
    "vllm-docs": "https://docs.vllm.ai",
    "unsloth-blog": "https://unsloth.ai/blog",
    "modal-blog": "https://modal.com/blog",
    "anyscale-blog": "https://www.anyscale.com/blog",
  };
  return sites[source] ?? "https://example.com";
}

function post(input: SeedInput): Content {
  const url = `${siteFor(input.source)}/${input.slug}`;
  return {
    id: contentId(input.source, url),
    source: input.source,
    sourceType: input.sourceType ?? "blog",
    title: input.title,
    url,
    publishedAt: input.date,
    ...(input.author ? { author: input.author } : {}),
    body: input.body,
    codeBlocks: input.codeBlocks ?? [],
    tags: input.tags ?? [],
  };
}

const now = "2026-08-20";

export const SEED_ITEMS: Content[] = [
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "How vLLM manages the KV cache with PagedAttention",
    slug: "latest/design/paged-attention",
    date: "2026-07-30",
    body: "PagedAttention keeps the key-value cache in fixed-size blocks managed by a block table, like OS paging. This eliminates memory fragmentation and gives near-zero waste, keys to serving long-context requests efficiently. The KV cache addresses are computed per block token index, enabling shared prefix coverage.",
    tags: ["kv cache", "paged attention"],
    codeBlocks: ["block_manager.allocate(seq_id, num_blocks)"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Automatic prefix caching with a radix tree",
    slug: "latest/design/prefix-caching",
    date: "2026-07-12",
    body: "Automatic prefix caching stores the KV cache of shared prompt prefixes in a radix tree so repeated system prompts and common tool instructions are never recomputed. Eviction uses a count-based LRU policy. Reduces decode latency for chat workloads with long system messages dramatically.",
    tags: ["prefix caching"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Speculative decoding: draft models and verification",
    slug: "latest/features/speculative",
    date: "2026-06-02",
    body: "Speculative decoding produces draft tokens from a small draft model, then the target model verifies them in a single parallel forward pass, accepting the longest prefix. Typical acceptance rates plus an expectation-based cache cut latency 2x in many shells. Works without changing the target model output.",
    tags: ["speculative decoding"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Continuous batching and request scheduling",
    slug: "latest/design/continuous-batching",
    date: "2026-05-20",
    body: "The scheduler adds and evicts requests at every decoding step, so a GPU never idles waiting for a straggler. Chunked prefill splits long prompts into chunks that interleave with ongoing decodes, keeping iteration-level scheduling fair across clients.",
    author: "engine team",
    tags: ["scheduling"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Quantization toolkits: AWQ, GPTQ, FP8 and Int8 checkpoints",
    slug: "latest/features/quantization",
    date: "2026-04-18",
    body: "Weight-only quantization with AWQ uses activation-aware calibration; GPTQ applies Hessian-informed rounding. FP8 supports both weights and activations on H100-class hardware. The marlin kernels make int4-on-fp16 kernels near zero-overhead and deploy-fast on the GPU.",
    tags: ["quantization", "awq", "gptq"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Tensor parallelism across multiple GPUs",
    slug: "latest/features/tp",
    date: "2026-03-09",
    body: "Tensor parallelism shards attention heads and weight matrices across GPUs with all-reduce between layers. The TP size trades the number of GPUs against the size of the allowed model. Support exists for NVLink and RDMA topologies.",
    tags: ["tensor parallelism"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "FlashAttention backends for long sequences",
    slug: "latest/features/flash-attn",
    date: "2026-02-26",
    body: "FlashAttention computes the exact softmax without materializing the whole attention matrix, making it IO-aware and fast, especially for long sequences. The flash-attn kernel backend is preferred for modern GPUs with fp8 and fp16 support.",
    tags: ["flashattention"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Serving Mixtral-style Mixture-of-Experts models",
    slug: "latest/design/moe",
    date: "2026-02-05",
    body: "Mixture-of-Experts models like Mixtral 8x7B reduce active parameters per token through top-k expert routing. Token routers select the top two experts. Expert-parallel scheduling improves throughput when the router and experts fit memory poorly.",
    tags: ["moe"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "Chunked prefill and the decode-prefill interleave",
    slug: "latest/design/chunked-prefill",
    date: "2026-01-14",
    body: "Chunked prefill splits prompt compute into chunks that interleave with short decode batches, preserving continuous batching style fairness between a heavy prompt and hundreds of small requests.",
    tags: ["continuous batching"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "docs",
    title: "High-throughput serving with the vLLM engine",
    slug: "latest/design/architecture",
    date: "2025-12-01",
    body: "vLLM's engine combines the paged KV cache, continuous batching and a chunked-prefill scheduler into an OpenAI-compatible serving stack, achieving extreme throughput against older batching layers.",
    tags: ["vllm"],
  }),
  post({
    source: "unsloth-blog",
    title: "How we make Llama 3.1 8B train in 4-bit VRAM",
    slug: "qlora-4bit-llama31",
    date: "2026-08-04",
    body: "Unsloth's 4-bit quantization layer uses dynamic gate-keeping so QLoRA fine-tuning fits 8B models in under 8GB. Works together with bfloat16 base weights and fast fused-optimizer kernels inside the GPU.",
    author: "Ning",
    tags: ["quantization", "fine-tuning"],
    codeBlocks: ["model = UnslothMistralForCausalLM.from_pretrained(weights, load_in_4bit=True)"],
  }),
  post({
    source: "unsloth-blog",
    title: "Mixture-of-Experts fine-tuning for a 8x7B class router",
    slug: "moe-finetuning",
    date: "2026-07-02",
    body: "Fine-tuning a Mixture-of-Experts model needs mindful top-k expert routing: gradients only flow through the selected experts, so expert imbalance can emerge. We test tricks to keep router utilization uniform on 8x7B style networks.",
    author: "Daniel",
    tags: ["moe"],
  }),
  post({
    source: "unsloth-blog",
    title: "DeepSeek-R1 distillation into 8B and 3B",
    slug: "deepseek-r1-distill",
    date: "2026-06-11",
    body: "Distillation lets a small student model imitate DeepSeek-R1's chain of thought. We trained distilled 8B and 3B and measured surprisingly close math scores for a fraction of the per-token cost.",
    author: "Ning",
    tags: ["distillation"],
  }),
  post({
    source: "unsloth-blog",
    title: "GGUF export and llama.cpp inference after fine-tuning",
    slug: "gguf-llamacpp",
    date: "2026-05-08",
    body: "Export your fine-tune straight to GGUF with embedded quantization metadata, then serve it on llama.cpp with the same 2-bit to 16-bit weight options. Speed-ups are mostly memory-bandwidth-bound.",
    author: "Ning",
    tags: ["quantization", "gguf"],
  }),
  post({
    source: "unsloth-blog",
    title: "Speculative decoding speeds up reasoning by 1.7x",
    slug: "speculative-grpo",
    date: "2026-04-03",
    body: "Running a draft model next to the policy during GRPO experiments turned speculative decoding downstream of the training loop into a near-free latency win. The verification pass accepts most drafts out of the box.",
    author: "Daniel",
    tags: ["speculative decoding"],
  }),
  post({
    source: "unsloth-blog",
    title: "What 4-bit versus 8-bit quantization changes at inference",
    slug: "4bit-vs-8bit",
    date: "2026-03-21",
    body: "We benchmark 8-bit and 4-bit weight-only quantization on the same MoE router and attention blocks. 4-bit doubles throughput but the calibration data decides whether outliers survive. Group-wise scaling is critical.",
    author: "Ning",
    tags: ["quantization"],
  }),
  post({
    source: "unsloth-blog",
    title: "Learning the KV cache within fine-tuning loops",
    slug: "kvcache-loop",
    date: "2026-02-13",
    body: "Long context fine-tuning leaks into the KV cache: with paged attention and prefix caching we halved the memory cost of repeated system prompts in endless eval loops on llama.cpp and Unsloth. Paged kv memory is now standard.",
    author: "Ning",
    tags: ["kv cache"],
  }),
  post({
    source: "unsloth-blog",
    title: "Distill everything: the instructor student recipe",
    slug: "distill-recipe",
    date: "2026-01-27",
    body: "Knowledge distillation follows a teacher-student setup where the teacher's soft targets are matched by a student model with fewer parameters. We publish the small student checkpoints for math and code.",
    author: "Daniel",
    tags: ["distillation"],
  }),
  post({
    source: "unsloth-blog",
    title: "FlashAttention in patchified LLaVA pipelines",
    slug: "flashattention-lavaps",
    date: "2025-12-15",
    body: "FlashAttention attention kernels bring exact softmax back into vision-language training. Combined with new Triton fusion, memory stays flat when the prompt embeds thousands of image patches. Keep the kernel language on GPU.",
    author: "Ning",
    tags: ["flashattention"],
  }),
  post({
    source: "modal-blog",
    title: "Serving vLLM with spec decoding on Modal",
    slug: "serving-vllm-spec",
    date: "2026-08-10",
    body: "We run production vLLM instances on Modal with an EAGLE draft model for speculative decoding. The GPU under adaptive concurrency serves open-weight models behind an OpenAI-compatible endpoint on the internet.",
    author: "Modal Labs",
    tags: ["vllm", "serving"],
  }),
  post({
    source: "modal-blog",
    title: "FlashAttention 2 for 128k contexts",
    slug: "flash-attn-128k",
    date: "2026-07-21",
    body: "FlashAttention 2's IO-aware attention is the standard way to process 128k token sequences without hoisting the matrix into HBM twice. In production we pair it with paged attention and context quantization for extreme throughput.",
    author: "Modal Labs",
    tags: ["flashattention", "long context"],
  }),
  post({
    source: "modal-blog",
    title: "Tensor parallel deploy of a 70B across 8 GPUs",
    slug: "tp-8gpu-70b",
    date: "2026-06-27",
    body: "Splitting a 70B inference workload into tensor-parallel shards across 8 GPUs on one node, with all-reduce in the attention and MLP layers. Memory per shard shrinks and the latency profile stays good on the GPU interconnect.",
    author: "Modal Labs",
    tags: ["tensor parallelism"],
  }),
  post({
    source: "modal-blog",
    title: "Writing Triton kernels for custom MoE routing",
    slug: "triton-moe",
    date: "2026-05-30",
    body: "A custom Triton kernel replaces the default top-2 gather-scatter in a Mixture-of-Experts router, cutting a 30%-of-step cost to 8%. The kernel is portable across GPU generations and torch.compiled into the serving path.",
    author: "Modal Labs",
    tags: ["moe", "gpu kernels"],
    codeBlocks: ["@triton.jit def topk_gate(x, w): ..."],
  }),
  post({
    source: "modal-blog",
    title: "Prefix caching for 100k-token prompts",
    slug: "prefix-cache-100k",
    date: "2026-04-29",
    body: "Code assist sessions re-send a 100k-token prefix every turn. Automatic prefix caching reuses the KV cache of shared prefixes and decode time collapses. The radix tree eviction policy keeps memory sane.",
    author: "Modal Labs",
    tags: ["prefix caching", "long context"],
  }),
  post({
    source: "modal-blog",
    title: "CUDA kernel fusion in an inference stack",
    slug: "kernel-fusion",
    date: "2026-03-17",
    body: "Fusing the embedding lookup, tokenizer and the first attention layer into one CUDA kernel removes launch overhead from the critical path. For memory-bandwidth-bound models the difference is large on the GPU.",
    author: "Modal Labs",
    tags: ["gpu kernels"],
  }),
  post({
    source: "modal-blog",
    title: "Continuous batching on serverless GPU pools",
    slug: "cont-batching-spot",
    date: "2026-02-20",
    body: "Continuous batching keeps GPU utilization flat when spot instances come and go. The scheduler's iteration-level slots absorb spot interruptions and remain fair to long prompts.",
    author: "Modal Labs",
    tags: ["continuous batching"],
  }),
  post({
    source: "modal-blog",
    title: "Speculative decoding with small draft models",
    slug: "spec-draft-small",
    date: "2026-01-09",
    body: "Small draft models give a 2x decode speed-up with zero novelty loss: the target model verifies every draft in parallel and only the accepted prefix is emitted.",
    author: "Modal Labs",
    tags: ["speculative decoding"],
  }),
  post({
    source: "modal-blog",
    title: "Running llama.cpp GGUF on constrained GPUs",
    slug: "llamacpp-gguf",
    date: "2025-12-02",
    body: "llama.cpp with GGUF quantized weights runs big models on small consumer GPUs. Memory band width dominates the 4-bit decode benchmark, so quantization stays the single biggest lever.",
    author: "Modal Labs",
    tags: ["quantization"],
  }),
  post({
    source: "anyscale-blog",
    title: "What is vLLM: high-throughput LLM serving",
    slug: "what-is-vllm",
    date: "2026-08-06",
    body: "vLLM introduced paged attention and continuous batching to the serving world and became the default engine for OpenAI-compatible endpoints. This article walks the architecture from KV cache blocks to the scheduler.",
    author: "Ahmad Qaja",
    tags: ["vllm", "serving"],
  }),
  post({
    source: "anyscale-blog",
    title: "MoE inference: navigating the mixture-of-experts landscape",
    slug: "moe-inference",
    date: "2026-07-07",
    body: "Mixture-of-Experts inference needs careful routing: top-k gate utilization, expert parallelism and memory placement all change the cost per request. We outline the knobs that matter for 8x7B-class models.",
    author: "Anyscale",
    tags: ["moe"],
  }),
  post({
    source: "anyscale-blog",
    title: "KV cache memory pressure and the paging solution",
    slug: "kv-cache-paging",
    date: "2026-06-19",
    body: "Cache fragmentation was the hidden wall in LLM serving. The KV cache with paged attention reclaims fragment space, and prefix caching reuses shared cursors. Together they 4x the number of concurrent requests.",
    author: "Ahmad Qaja",
    tags: ["kv cache", "paged attention"],
  }),
  post({
    source: "anyscale-blog",
    title: "Speculative decoding profiling across engines",
    slug: "spec-profiling",
    date: "2026-05-26",
    body: "We profile speculative decoding across vLLM and TensorRT-LLM: acceptance rate, draft-vs-verify overhead, and the cold-start cost of the draft model. Draft-and-verify wins only when the draft costs less than it saves.",
    author: "Anyscale",
    tags: ["speculative decoding"],
  }),
  post({
    source: "anyscale-blog",
    title: "Continuous batching explained with Orca",
    slug: "cont-batch-orca",
    date: "2026-04-09",
    body: "The Orca paper showed iteration-level scheduling for batching, the ancestor of today's continuous batching. Steps pick new requests at every decode slot instead of waiting for the batch to finish.",
    author: "Anyscale",
    tags: ["continuous batching"],
  }),
  post({
    source: "anyscale-blog",
    title: "Tensor parallelism on Ray at the 100M-token scale",
    slug: "ray-tp",
    date: "2026-03-04",
    body: "Ray orchestrates tensor-parallel workers for a 405B model across 40 nodes. All-reduce over RDMA links and a checkpointed kv cache keep the serving tier stable during pipeline rolling.",
    author: "Anyscale",
    tags: ["tensor parallelism"],
  }),
  post({
    source: "anyscale-blog",
    title: "Long-context serving with YaRN and Ring Attention",
    slug: "long-context-yarn",
    date: "2026-02-11",
    body: "YaRN extrapolates RoPE for longer context windows, while ring attention splits the sequence across machines. Both raise the ceiling on KV cache pressure for long-context serving.",
    author: "Anyscale",
    tags: ["long context"],
  }),
  post({
    source: "anyscale-blog",
    title: "A guide to quantization for production serving",
    slug: "quant-serving-guide",
    date: "2026-01-16",
    body: "AWQ, GPTQ and FP8 are currently the three production quantization paths. Calibration data, group size and the kernel backend change quality-per-GPU-second performance dramatically at the same bit-width.",
    author: "Anyscale",
    tags: ["quantization"],
  }),
  post({
    source: "anyscale-blog",
    title: "FlashAttention: efficient attention, no magic",
    slug: "flashattention-explained",
    date: "2025-12-08",
    body: "FlashAttention's tiled IO-aware approach computes the exact attention softmax without materializing the matrix, which is why long-context training got cheap. The kernels are a standard part of every modern stack.",
    author: "Anyscale",
    tags: ["flashattention"],
  }),
  post({
    source: "anyscale-blog",
    title: "Engine evolution: from TGI to vLLM to SGLang",
    slug: "engine-evolution",
    date: "2025-11-19",
    body: "The serving frameworks race: TGI pioneered throughput tricks, vLLM weaponized the paged KV cache, SGLang adds a shared scheduler with radix-tree prefix caching and raid planning.",
    author: "Ahmad Qaja",
    tags: ["serving-frameworks"],
  }),
  post({
    source: "anyscale-blog",
    title: "Digging into GPU kernels for LLM inference",
    slug: "gpu-kernel-deep-dive",
    date: "2025-10-27",
    body: "Deconvolution of a decode kernel: memory-bandwidth-bound compute, warp-level tiling, and the hidden cost of launch overhead. Triton and CUDA both matter downstream of the model.",
    author: "Anyscale",
    tags: ["gpu kernels"],
  }),
  post({
    source: "anyscale-blog",
    title: "PagedAttention: managing KV cache for long-context LLM serving",
    slug: "pagedattention-paper",
    date: "2025-09-15",
    body: "The PagedAttention paper (SOSP 2023) introduced block tables for the KV cache, removing fragmentation and enabling near-zero waste memory. It remains the intellectual core of serving frameworks such as vLLM.",
    author: "Anyscale",
    tags: ["kv cache", "paged attention"],
  }),
  post({
    source: "anyscale-blog",
    title: "Distillation workflows that actually transfer reasoning",
    slug: "distill-reasoning",
    date: "2025-08-21",
    body: "Distilling reasoning from DeepSeek-R1 into smaller models works when the teacher's distributions are captured by a student with matching vocab. We share the eval harness and the student recipes.",
    author: "Anyscale",
    tags: ["distillation"],
  }),
  post({
    source: "anyscale-blog",
    title: "Mixtral 8x7B in the cloud: router and memory budgets",
    slug: "mixtral-routing",
    date: "2025-07-30",
    body: "Mixtral 8x7B's expert routing activates 2 of 8 experts per token, so the router is cheap but expert memory is heavy. Right-sized quantization of unused experts is the profitable exception rather than the rule.",
    author: "Anyscale",
    tags: ["moe"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "changelog",
    title: "vLLM v0.9.0 changelog: chunked prefill by default",
    slug: "changelog/0.9",
    date: "2025-11-04",
    body: "Chunked prefill now runs interleaved with decodes by default, improving continuous batching fairness. New int4 marlin kernels, and the prefix-caching radix tree ships with a policy evaluator.",
    tags: ["changelog"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "changelog",
    title: "vLLM v0.11.0 changelog: speculative decoding coverage",
    slug: "changelog/0.11",
    date: "2026-04-02",
    body: "Speculative decoding now spans draft models with targeted KV cache corrections. Expectation-based decode starts from the longest common prefix. See the scheduler section for the chunked-prefill tuning knobs.",
    tags: ["changelog"],
  }),
  post({
    source: "vllm-docs",
    sourceType: "changelog",
    title: "vLLM v0.12.0 changelog: automatic prefix caching GA",
    slug: "changelog/0.12",
    date: "2026-06-24",
    body: "Automatic prefix caching is production-ready with the radix-tree cache and LRU eviction. FlashAttention kernel coverage extends to Blackwell fp8 paths and the long-context window defaults to 128k.",
    tags: ["changelog"],
  }),
  post({
    source: "unsloth-blog",
    title: "KV cache and attention: how decoding actually works",
    slug: "kv-attention-primer",
    date: "2026-07-17",
    body: "A primer on the KV cache for people new to attention: during decode each step needs the previous tokens' key and value tensors. Caching them is the difference between O(n) and O(n²) compute per token.",
    author: "Daniel",
    tags: ["attention", "kv cache"],
  }),
  post({
    source: "unsloth-blog",
    title: "MoE with top-k routing by hand",
    slug: "moe-primer",
    date: "2026-06-05",
    body: "How Mixture-of-Experts works: a tiny router scores all experts, top-k experts run, and the outputs are weighted. Token-level routing keeps per-token FLOPs far below the parameter budget.",
    author: "Daniel",
    tags: ["moe", "attention"],
  }),
  post({
    source: "modal-blog",
    title: "The decode phase and why attention memory is the wall",
    slug: "decode-attention-memory",
    date: "2026-07-06",
    body: "After prefill, decoding is memory-bound: the KV cache is re-read every step. This is why attention read throughput and cache compression decide your tokens-per-second more than FLOPs.",
    author: "Modal Labs",
    tags: ["attention", "kv cache"],
  }),
  post({
    source: "anyscale-blog",
    title: "Tensor weight and memory in parallelism: a survey",
    slug: "parallelism-landscape",
    date: "2025-12-11",
    body: "Pipeline parallelism splits layers, tensor parallelism splits the matrix multiplication and sequence parallelism splits attention along tokens. Serving 100B+ models requires the right composition of all three under the same kv-cache budget.",
    author: "Anyscale",
    tags: ["tensor parallelism"],
  }),
  post({
    source: "unsloth-blog",
    title: "Training small student models that punch above their size",
    slug: "student-models",
    date: "2026-02-27",
    body: "Student models trained by distillation inherit most of the teacher's soft-label signal. Combined with 4-bit quantization the student becomes the cost-effective production shape for repetitive tasks.",
    author: "Daniel",
    tags: ["distillation", "quantization"],
  }),
  post({
    source: "modal-blog",
    title: "One GPU, 200k context: paged kv wins again",
    slug: "200k-paged-kv",
    date: "2026-06-16",
    body: "Running a 200k-token context on one GPU is impossible without paged attention: the block table slack plus a 3-bit kv cache squeeze it to fit. The decode of shared prefix costs a single pass thanks to prefix caching.",
    author: "Modal Labs",
    tags: ["long context", "kv cache", "paged attention"],
  }),
  post({
    source: "anyscale-blog",
    title: "LLM inference in 2026: what changed and what moved",
    slug: "2026-inference",
    date: "2026-08-12",
    body: "Speculative decoding moved to draft heads, MoE serving became mainstream, and long-context serving converged on paged kv plus prefix caching. Continuous batching is table stakes; quantization now includes fp4 training.",
    author: "Ahmad Qaja",
    tags: ["trend"],
  }),
  post({
    source: "anyscale-blog",
    title: "Attention without full materialization: from FlashAttention to the future",
    slug: "attention-future",
    date: "2026-05-05",
    body: "FlashAttention changed the attention cost curve, and post-MLA engines reuse KV reliably. The next step is a cache hierarchy aware of the radix tree, proving IO-aware attention wins twice.",
    author: "Anyscale",
    tags: ["flashattention", "attention"],
  }),
  post({
    source: "unsloth-blog",
    title: "llama.cpp and 4-bit GGUF: the consumer inference stack",
    slug: "gguf-consumer",
    date: "2026-03-28",
    body: "GGUF quantization in llama.cpp lets 4-bit 70B models run on a single consumer GPU. Awq and gptq are production alternatives in the same ecosystem, but GGUF stays the default for local use.",
    author: "Ning",
    tags: ["quantization"],
  }),
];

export { now };
